# Generated by Django 2.2.19 on 2021-04-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="surname",
            field=models.TextField(blank=True, null=True),
        ),
    ]
